apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: ghcr.io/terry620033/hello-app:14a73d6344b009aeb029f5ae2311965f5a6b2a26
        ports:
        - containerPort: 5000
