apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: ghcr.io/terry620033/hello-app:adeefa998f398de7fb571448f4b681a193c00c8c
        ports:
        - containerPort: 5000
